---
title: "Downloading the occurrence data"
author: "Jo-Hannes Nowé"
output: 
  pdf_document: default
  html_document: default
---



# Loading the required packages
```{r}
library(dplyr)
library(sf)
library(ggplot2)
library(lubridate)
library(stringr)
library(ows4R)
library(readr)
library(CoordinateCleaner)
```

```{r}
alldataset <- read.csv(file.path(datadir,"allDatasets.csv"))
list_dasid <- alldataset$datasetid

wfs <- WFSClient$
  new("https://geo.vliz.be/geoserver/Dataportal/wfs", "2.0.0", logger = "INFO")$
  getCapabilities()$
  findFeatureTypeByName("Dataportal:eurobis-obisenv_full")
dir.create(file.path(occdir,"target_group"))
for(datasetid in list_dasid){
params <- paste0("where%3Adatasetid+IN+%28",
                 datasetid,
                 "%29")

feature_pagination <- wfs$getFeatures(viewParams = params, paging = TRUE, paging_length = 50000)
filename = paste0("dataset", datasetid,".csv")
#Save the download to a csv file with the dataset and region name
write_delim(feature_pagination, file.path(occdir,"target_group", filename), delim = ",")
}


#Still need to load the last 2 but will already try
target_files <- list.files(file.path(occdir,"target_group/"))
dataframes_target <- list()

for(file in target_files) {
  # Read the CSV file into a dataframe
  df <- read.csv(file.path(occdir,"target_group/",file))
  
  #Append the dataframe to the list
  dataframes_target <- c(dataframes_target, list(df))
}
target_background <- do.call(rbind,dataframes_target)
target_background <- data.frame(target_background)%>%
  filter(class=="Mammalia")%>%
  filter(scientificnameaccepted!="Phocoena phocoena")

load(file.path(datadir,"study_area.RData"))
ggplot(data=study_area)+
  geom_sf()+
  geom_point(data=target_background,x=target_background$decimallongitude,y=target_background$decimallatitude)
```
Need to further clean up the target_background dataframe. 


```{r}
absence <- target_background%>%
  dplyr::mutate(occurrenceStatus = 0,day = day(datecollected),month = month(datecollected),year=year(datecollected))%>%
  filter(!is.na(datecollected))%>%
  filter(year>1999)%>%
  filter(year<2020)%>%
  arrange(datecollected)%>%
  mutate(year_month=paste(year,month,sep='-'))%>%
  mutate(year_month=factor(year_month,levels=unique(year_month),ordered=TRUE))%>%
  mutate(copydecimallongitude = decimallongitude, copydecimallatitude=decimallatitude)%>%
  dplyr::select(scientificnameaccepted,decimallongitude,decimallatitude,datecollected,
         occurrenceStatus,day,month,year,year_month,copydecimallongitude,copydecimallatitude)
absence <-  st_as_sf(absence,coords = c("copydecimallongitude", "copydecimallatitude"), 
           crs = st_crs(study_area))
within_abs <- st_contains(study_area,absence)[[1]]
absence <- absence[within_abs,]
absence <- cc_dupl(absence, lon = "decimallongitude", lat = "decimallatitude",
                        value = "clean",species="scientificnameaccepted", additions=
                 "datecollected")
```




```{r, fig.width=8, fig.height=12}
puntdata <- absence%>%
  filter(year>1999)%>%
  filter(year<2006)%>%
  mutate(year=factor(year),month=factor(month))

for (jaar in levels(puntdata$year)){
  plotdata <- puntdata %>%
    filter(year==jaar)#%>%
   # mutate(month=factor(month,levels=new_order))
  
plot<-ggplot(data=study_area) +
    geom_sf()+
    theme_minimal()+
    geom_point(data=plotdata, aes(x=decimallongitude,y=decimallatitude,colour="red"),show.legend=FALSE) +
    theme(plot.title = element_text(size=20), axis.title= element_text(size = 16),
          text = element_text(size = 16))+
    labs(title = paste("target group records",jaar))+
    facet_wrap(~month, nrow= 4)+
    theme_void()+
    theme(strip.background=element_blank(), #remove strip background
          strip.text= element_text(size=12))
print(plot)
}

```

```{r}
save(absence, file=file.path(datadir,"absence.RData"))
```

