---
title: "Download Copernicus Marine data"
author: "Jo-Hannes Nowé"
output: 
  pdf_document: default
  html_document: default
---


# Set-up of the python environment
```{r}
library(reticulate) #reticulate package allows for python usage in R 
virtualenv_create("mbo-proj",force=FALSE) #create a virtual environment to install packages in
py_install("copernicusmarine",envname = "mbo-proj") #the copernicusmarine package allows CMEMS downloads
virtualenv_list() #Check the list of available environments
use_virtualenv("mbo-proj") #Load the environment
```
More information on the reticulate package on: https://rstudio.github.io/cheatsheets/reticulate.pdf

Overview of the functions can be found at: https://help.marine.copernicus.eu/en/collections/9080063-copernicus-marine-toolbox

How to configure the credentials can be found at: https://help.marine.copernicus.eu/en/articles/8185007-copernicus-marine-toolbox-credentials-configuration
Works in the terminal. Needs to be done only once. 


```{r}
bbox <-sf::st_bbox(spatial_extent)
xmin <- bbox[[1]]
xmax <- bbox[[3]]
ymin <- bbox[[2]]
ymax<- bbox[[4]]
time_start <- int_start(temporal_extent)
time_end <- int_end(temporal_extent)
parsed_datetime <- ymd_hms(time_start, tz = "UTC")

# Format the POSIXct object into the desired string format
formatted_datetime <- format(parsed_datetime, "%Y-%m-%dT%H:%M:%S")
```

```{python}
print(r.xmin)
```



```{python}
import copernicusmarine as cm

#?cm.subset
cm.subset(
  dataset_id="cmems_mod_glo_phy_my_0.083deg_P1M-m",
  variables=["so", "thetao"],
  minimum_longitude=r.xmin,
  maximum_longitude=r.xmax,
  minimum_latitude=r.ymin,
  maximum_latitude=r.ymax,
  start_datetime=r.date_start,
  end_datetime=r.date_end,
  minimum_depth=0.49402499198913574,
  maximum_depth=0.49402499198913574,
  netcdf_compression_enabled=True,
  output_directory= "data/raw_data/",
  output_filename="tempsal.nc",
  overwrite_output_data = True,
  force_download=True)


```
```{r}
library(terra)
tempsal <- rast('data/raw_data/tempsal.nc')
plot(tempsal)
```



```{python}
cm.subset(
  dataset_id="cmems_mod_glo_bgc_my_0.083deg-lmtl_PT1D-i",
  variables=["npp"],
  minimum_longitude=r.xmin,
  maximum_longitude=r.xmax,
  minimum_latitude=r.ymin,
  maximum_latitude=r.ymax,
  start_datetime=r.date_start,
  end_datetime=r.date_end,
  minimum_depth=0.5057600140571594,
  maximum_depth=0.5057600140571594,
  netcdf_compression_enabled=True,
  output_directory= "data/raw_data/",
  output_filename="npp.nc",
  overwrite_output_data = True,
  force_download=True)

```



