---
title: "Tidymodels ensemble approach"
author: "Jo-Hannes Nowé"
output: 
html_document:
  toc=TRUE
---

# Loading the required packages
```{r}
library(tidymodels)
#devtools::install_github("jiho/autoplot")
library(autoplot)
library(stacks) #for ensembling the individual models together
library(workflows)
library(ranger) #for the randomforest model
library(mgcv) #for the GAM model
library(xgboost) #for the xgboost model
library(earth) #for the MARS model
```

```{r}
model <- readRDS(file.path(datadir,"stacked_model.rds"))
```

```{r}
PAdata <- file.path("data","PA_env.RData")
load(PAdata)
#Turn our occurrence into a factor so that there are two known levels, either
#present or absent.
data$occurrenceStatus<-factor(data$occurrenceStatus)

#Wrm maken we dit weer in een tibble?
data <- as_tibble(data)%>%
  dplyr::select(c(-ID,-scientificname))
data
```

```{r}
set.seed(222)
#Put 4/5 in the training set
data_split<- initial_split(data, prop=4/5)

#Create data frames for the two sets:
train_data <- training(data_split)
test_data <- testing(data_split)
```




```{r}
model #this is the model
library(caret) #without this it might give an error trying to use a predict function from another package
library(stacks)
stack_fit <-
  model %>%
  fit_members()

prediction <- predict(model,test_data)%>%
  bind_cols(predict(model,test_data, type="prob")) %>%
  bind_cols(test_data %>%
              dplyr::select(occurrenceStatus))
prediction

```


# Prepare environmental data
```{r}
#Make a custom function that can be used with the terra::predict function
predprob <- function(...) predict(...,type="prob")$.pred_1
#Try out how to make this one work as well
predmem <- function(...) predict(..., type="prob",members=TRUE)
```

#For monthly maps using the same rasters as it was build on

```{r}
#Load the different layers (see environmental clean script)
temp
sal
mean_npp
bathy

#Different layers, crop them to the same extent of bathy
temp <- crop(temp,bathy) #layer1: 1999-01-01 -> layer270: 2021-06-01
sal <- crop(sal,bathy)#layer1: 1999-01-01 -> layer270: 2021-06-01
mean_npp <- crop(mean_npp,bathy)#layer1: 1999-01-01 -> layer288: 2022-12-31
ext(bathy) <- ext(temp) #because there where small differences and then we can't combine them
bathy <- resample(bathy, temp) #because after the change in extent we couldn't combine them without resampling bathy as its resolution changed
monthly_prediction <- list()
#Loop over every monthy layer (Takes +-1 min for 12 months)
for(i in 1:270){
  #Get out the right monthly layer and combine them together in a new spatraster that contains one layer for each predictor
  monthly_info <- c(temp[[i]],sal[[i]],mean_npp[[i]],bathy)
  #Delete the NA values
  mask <- !is.na(monthly_info)
  monthly_info <- terra::mask(monthly_info,mask)
  #To make sure the names of the layers correpond to the names the model was trained on
  names(monthly_info) <- c(
            "temp",
            "sal","npp","bathy")
  monthly_prediction[[i]] <- predict(monthly_info,model,fun=predprob,na.rm=TRUE)
}
#To turn it into a raster layer  
monthly_prediction <- rast(monthly_prediction)

ggplot()+
  geom_spatraster(data=monthly_prediction[[240]])+
  scale_fill_viridis_c()#tidyterra package makes this possible

#Write the monthly predictions into tif files for use in Rutendo's shiny app
for(i in 1:nlyr(monthly_prediction)){
filepath <- file.path(datadir,"species_rasters","monthly",paste0("Month",i,".tif"))
  writeRaster(monthly_prediction[[i]],filepath,overwrite=TRUE)  
}



testmonthlyraster <- raster(file.path(datadir,"species_rasters","monthly","Month3.tif"))
plot(testmonthlyraster)
```
```{r}
for(i in 1:12){
  ggplot()+
  geom_spatraster(data=mean_prediction[[1]])+
    scale_fill_viridis_c(limits = c(0, 1), name = "Habitat suitability")+
    ggtitle(paste0("Month ",i))
}

ggplot()+
  geom_spatraster(data=mean_prediction[[12]])+
    scale_fill_viridis_c(limits = c(0, 1), name = "Habitat suitability")+
    ggtitle(paste0("Month ",i))
```

```{r}
#monthly_means
monthly_seq <- rep(1:12,length.out=nlyr(monthly_prediction))
monthly_dataset <- split(monthly_prediction,monthly_seq)
monthly_dataset
mean_prediction<-list()
for(i in 1:length(monthly_dataset)){
  mean_prediction[[i]] <- app(monthly_dataset[[i]],fun=mean)}

for(i in 1:length(mean_prediction)){
filepath <- file.path(datadir,"species_rasters","monthly_mean",paste0("Monthly_mean",i,".tif"))
  writeRaster(mean_prediction[[i]],filepath,overwrite=TRUE)  
  }
```


```{r}
#Plotting an anmiated visual, gganimate is nice but not feasible for rasterdata yet, maybe with gifski for creating stopmotion but this package can't be downloaded
library(gganimate)

# Create separate plots
plotlist <- list()
for(i in 1:12){
  plotlist[[paste0("Plot",i)]] <- ggplot()+
  geom_spatraster(data=mean_prediction[[i]])+
    scale_fill_viridis_c(limits = c(0, 1), name = "Habitat suitability")+
    ggtitle(paste0("Month ",i))
}

#Storing the different frames in a folder
for (i in seq_along(plotlist)) {
  filename <- file.path(datadir,"plots","frames",paste0("plot", i, ".png"))
  png(filename)
  print(plotlist[[i]])
  dev.off()
}


library(magick)
# Read PNG files
image<-list()
for(i in 1:12){
image[[i]] <- image_read(file.path(datadir,"plots","frames",paste0("plot", i, ".png")))
}


# Create GIF
gif <- image_join(image)
animated_gif <- image_animate(gif,fps=2)
image_write(animated_gif,file.path(datadir,"plots","monthly_pred.gif"))
```

