name: make
on:
  release:
    types: [ published ]
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  schedule:
    - cron: '0 4 5,25 * *'

jobs:
  call-build-container:
    uses: ./.github/workflows/build-container.yml
    with:
      oci_tag: ghcr.io/qcdis/habitat_suitability_model
      version: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      push: ${{ github.event_name == 'release' }}